import qs from 'qs';

import * as errors from '../common/errors.js';

export function query(userId, method, params = {})
{
	return new Promise((resolve, reject) =>
	{
		const xhr = new XMLHttpRequest;

		xhr.onreadystatechange = () =>
		{
			if (xhr.readyState !== XMLHttpRequest.DONE)
			{
				return;
			}

			const response = JSON.parse(xhr.responseText);

			if (xhr.status === 200)
			{
				resolve(response);
			}
			else
			{
				if (response.hasOwnProperty('_errors'))
				{
					reject(new errors.UserError(...response._errors));
				}
				else
				{
					reject('An unknown error has occurred.');
				}
			}
		}

		xhr.open('POST', '/api/' + method);

		if (params instanceof FormData)
		{
			// For queries generated by <Form>
			xhr.send(params);
		}
		else
		{
			// For queries generated by _getLoaderFunction
			xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
			xhr.send(qs.stringify(params));
		}
	});
}